// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywngmxbydriputmjaomu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3bmdteGJ5ZHJpcHV0bWphb211Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MzQzNjMsImV4cCI6MjA2NDUxMDM2M30.XIaFXrkPu8IZzmSWwumuHx-hV4ofP9aXYducKYzVZOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);